client_timeout_secs = 120

[[servers]]
server_address = "127.0.0.1"
ports = [8080, 8081]
server_name = "localhost"
root = "routes"

  [servers.routes."/"]
  filename = "home.html"
  methods = ["post", "get"]

  [servers.routes."/old-page".redirect]
  to = "/"
  code = 302

  [servers.routes."/static"]
  directory = "static"
  directory_listing = true
  upload_dir = "static"
  methods = ["get", "post", "delete"]

  [servers.routes."/root"]
  directory = ""
  directory_listing = true
  methods = ["get", "post", "delete"]
  
[[servers]]
server_address = "127.0.0.1"
server_name = "anotherhost"
ports = [8080]
